### ISSUE TITLE
push_logs.sh won't send the web server logs

### ISSUE THREAD

**Issue by letompouce** [bibliosansfrontieres/ideascube-cleanup-configure#1]
In [`ideascube-cleanup-configure`](https://github.com/bibliosansfrontieres/ideascube-cleanup-configure/blob/01e328b51a9019e78cf6c9dde9791a2fa9b7884e/roles/setup_system/templates/push_log.sh.j2#L14) the `push_logs.sh` script tries to push `/media/hdd/log/*`.

In [`olip-deploy`](https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/-/blob/2d856b5f641e92e40a0ccbded891cf278891ca22/roles/olip/tasks/stats.yml#L7) we create it as `/media/hdd/logs` - note the trailing S.

Therefore, logs are not found by `push_logs.sh` and are never pushed to our server.

Some solutions:
* rename `/media/hdd/logs` removing the trailing S - `olip-deploy` side
* or fix the path in the `push_logs.sh` script - `ideascube-cleanup-configure` side

**Comment by letompouce** [comment]
We will fix the `push_logs.sh` script in here.

Then, `olip-deploy` side we will implement a temporary workaround.

Later, a proper way to implement rolling hotfixes will be added to `olip-deploy`, which will allow us to clean everything up.

**Comment by fheslouin** [comment]
Fixed: https://github.com/bibliosansfrontieres/ideascube-cleanup-configure/commit/0d6b891d7a9c1c408a51ce48cf553135dda1fb67
Workaround for OLIP deploy playbook : https://gitlab.com/bibliosansfrontieres/olip/olip-deploy/-/merge_requests/54
